// Copyright (c) 2021 Jeevan James
// This file is licensed to you under the MIT License.
// See the LICENSE file in the project root for more information.

using System.Data;
using System.Diagnostics;

namespace Datask.Providers.Schemas;

[DebuggerDisplay("{Name,nq} : {DatabaseType,nq}")]
public class ColumnDefinition
{
    public ColumnDefinition(string name)
    {
        Name = name;
    }

    public string Name { get; }

    public string DatabaseType { get; set; } = null!;

    public Type Type { get; set; } = null!;

    public int MaxLength { get; set; }

    public DbType DbType { get; set; }

    public bool IsNullable { get; set; }

    public bool IsIdentity { get; set; }

    public bool IsPrimaryKey { get; set; }

    public bool IsAutoGenerated { get; set; }

    //[MemberNotNullWhen(true, nameof(ForeignKey))]
    public bool IsForeignKey => ForeignKey is not null;

    public ForeignKeyDefinition? ForeignKey { get; set; }
}
