SELECT
    c.TABLE_SCHEMA AS [Schema],
    c.TABLE_NAME AS [Table],
    c.COLUMN_NAME AS [Name],
    c.ORDINAL_POSITION AS [OrdinalPosition],
    c.DATA_TYPE AS [DbDataType],
    CONVERT(bit, CASE WHEN c.IS_NULLABLE = 'YES' THEN 1 ELSE 0 END) AS [IsNullable],
    CONVERT(bit, COLUMNPROPERTY(object_id(c.TABLE_SCHEMA + '.' + c.TABLE_NAME), c.COLUMN_NAME, 'IsIdentity')) AS [IsIdentity]
FROM INFORMATION_SCHEMA.COLUMNS c
INNER JOIN INFORMATION_SCHEMA.TABLES t ON
    c.TABLE_SCHEMA = t.TABLE_SCHEMA AND
    c.TABLE_NAME = t.TABLE_NAME
WHERE
    t.TABLE_TYPE = 'BASE TABLE'
ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION
