SELECT
    c.TABLE_SCHEMA AS [Schema],
    c.TABLE_NAME AS [Table],
    c.COLUMN_NAME AS [Name],
    c.ORDINAL_POSITION AS [OrdinalPosition],
    c.IS_NULLABLE AS [AllowNulls],
    c.DATA_TYPE AS [DbDataType]
FROM INFORMATION_SCHEMA.COLUMNS c
INNER JOIN INFORMATION_SCHEMA.TABLES t ON
    c.TABLE_SCHEMA = t.TABLE_SCHEMA AND
    c.TABLE_NAME = t.TABLE_NAME
WHERE
    t.TABLE_TYPE = 'BASE TABLE'
ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION
