using Datask.Providers;

namespace Datask.Tool.ExcelData.Core.Excel.Validator;

public abstract record ValidationDiff(DbObjectName Table);

// *** TABLE DIFFERENCES ***

public abstract record TableDiff(DbObjectName Table) : ValidationDiff(Table);

public sealed record NewTableDiff(DbObjectName Table) : TableDiff(Table);

public sealed record DeletedTableDiff(DbObjectName Table) : TableDiff(Table);

public sealed record RenamedTableDiff(DbObjectName Table) : TableDiff(Table);

// *** COLUMN DIFFERENCES ***

public abstract record ColumnDiff(DbObjectName Table, string Column) : ValidationDiff(Table);

public sealed record NewColumnDiff(DbObjectName Table, string Column) : ColumnDiff(Table, Column);

public sealed record DeletedColumnDiff(DbObjectName Table, string Column) : ColumnDiff(Table, Column);

public sealed record RenamedColumnDiff(DbObjectName Table, string Column) : ColumnDiff(Table, Column);

public sealed record ReorderedColumnDiff(DbObjectName Table, string Column, int OldIndex, int NewIndex)
    : ColumnDiff(Table, Column);

public sealed record MissingColumnMetadataDiff(DbObjectName Table, string Column) : ColumnDiff(Table, Column);

public sealed record ChangedColumnMetadataDiff<T>(
    DbObjectName Table,
    string Column,
    ColumnMetadata Metadata,
    T OldValue,
    T NewValue) : ColumnDiff(Table, Column);

public enum ColumnMetadata
{
    IsAutoGenerated,
    IsForeignKey,
    IsPrimaryKey,
}
